#!/bin/sh
#
#  CachedLynx - Runs Lynx using a proxy host
#
#  Usage: CachedLynx [Lynx Arguements]
#
#  Darren Hardy, University of Colorado - Boulder, August 1994
#
#  $Id: CachedLynx,v 1.1 1996/02/22 06:23:57 wessels Exp $
#

#  set cachehost to the machine running the Harvest Object cache
cachehost=localhost
cacheport=3128

http_proxy="http://${cachehost}:${cacheport}/"; export http_proxy
ftp_proxy="http://${cachehost}:${cacheport}/"; export ftp_proxy
gopher_proxy="http://${cachehost}:${cacheport}/"; export gopher_proxy

exec lynx ${@+"$@"}
